# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto_1/greet.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto_1/greet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto_2 import dependency_pb2 as proto__2_dot_dependency__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto_1/greet.proto\x12\x05greet\x1a\x18proto_2/dependency.proto\"E\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\'\n\tuser_info\x18\x02 \x01(\x0b\x32\x14.dependency.UserInfo\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2=\n\x07Greeter\x12\x32\n\x08SayHello\x12\x13.greet.HelloRequest\x1a\x11.greet.HelloReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_1.greet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=56
  _globals['_HELLOREQUEST']._serialized_end=125
  _globals['_HELLOREPLY']._serialized_start=127
  _globals['_HELLOREPLY']._serialized_end=156
  _globals['_GREETER']._serialized_start=158
  _globals['_GREETER']._serialized_end=219
# @@protoc_insertion_point(module_scope)
